### ISSUE TITLE
Image is broken

### ISSUE THREAD

**Issue by bookercodes** [oh-my-fish/theme-zish#1]

**Comment by wzhishen** [comment]
Fixed.

**Comment by bookercodes** [comment]
Nice one, mate.

**Comment by bobthecow** [comment]
Ohhh, this one broke because it's using a preview image inside the repo. Most of the more recent ones use an image uploaded to the GitHub CDN.

@bpinto Do we want to change that policy now that it won't weigh down the main repo?

**Comment by bpinto** [comment]
@bobthecow I wouldn't mind having the images inside the repo now. But I guess not having them is better. Perhaps we should always use an image uploaded in github?

**Comment by bobthecow** [comment]
Having them in the repo isn't a horrible thing, since it's a lot more apparent where they come from. Especially with everything scattered out into different repos, with a lot more maintainers, it'd be a lot harder to socially enforce the current convention. I'd say start putting them in the repos themselves.

**Comment by bpinto** [comment]
I know, but what if someone adds a 3mb image to the repo? Then a 5kb repo will become 3mb+ only because of an image? I can't find that good. :(
